name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  platform-ci:
    permissions:
      contents: read
      packages: write
    uses: Nizar835/platform-demo-lab1/.github/workflows/ci-nizar835.yml@patch-1
